### ISSUE TITLE
Nvim API now supports buffer update events

### ISSUE THREAD

**Issue by justinmk** [Chillee/VSCodeNeovim#13]
README.md mentions:

> Important Neovim PRs to follow: https://github.com/neovim/neovim/pull/5269 Text Diffs (so we don't have to sync the entire buffer each time)

That PR (https://github.com/neovim/neovim/pull/7917) was merged. 

summon @Chillee

**Comment by lunixbochs** [comment]
actualvim has a reference implementation if that helps: https://github.com/lunixbochs/ActualVim/commit/414e8d4c3feb4c798a611c14ef47741e8b952146

**Comment by billyvg** [comment]
Here's a PR for the node client: https://github.com/neovim/node-client/pull/81

**Comment by justinmk** [comment]
Not needed anymore, now that https://github.com/asvetliakov/vscode-neovim exists.
