### ISSUE TITLE
Package neovim binaries for all platforms within extension

### ISSUE THREAD

**Issue by xconverge** [Chillee/VSCodeNeovim#7]
I think that the neovim binaries for Linux, MacOs, and Windows should be packaged with the extension.

This will eliminate any dependencies/configuration/wrong versions at the price of a slightly larger package size.

This will also simplify readme/setup for the user.

**Comment by ghost** [comment]
It would make the vsix pretty big and would have a lot of redundant files for most users.

Also, most users who will use this plugin will have some experience with Vim, and have it most likely installed already, so installing NeoVim wouldn't be that hard to do.

Then there's the security factor. Having a binary distributed with an extension for a text editor is a no-no for most Linux users.

**Comment by xconverge** [comment]
Feel free to treat this as a user story and thumbs up/down accordingly

As a developer, we get quite a few people with incompatible versions installed. Perhaps the effort could be spent elsewhere in verifying that a) nvim is found and b) a version check on it otherwise dont activate the extension and show an error infobar saying what happened.

Unfortunately as we develop this extension, we will also be creating PRs and feature requests for neovim. Without packaging binaries, we will need to wait for a required feature to hit stable release of neovim before releasing an updated version of this extension, and then at that point anyone with the older version of neovim will hit the above error and need to upgrade neovim or downgrade the vscode extension...

**Comment by ghost** [comment]
OK, I see your point, but would it be possible to download the binary during runtime? Check if neovim is available, and if not, download the required version. That way the extensions wouldn't be shipped with 3 different binaries for all platforms and the required dependencies, but only for one and only if necessary.

**Comment by xconverge** [comment]
Yes that is possible :) I just don't really like the idea of messing with peoples installed neovim version, that would be very uncool of us. Having the binary contained would mean this extension just works in it's own world, and has nothing to do with what you have installed.

I think for starters putting a check makes sense, then we can get a gauge on how many people run into setup issues and that error message and are unable to resolve it.

**Comment by Chillee** [comment]
@paxy97 the 2 things that ameliorate your concerns are 1. Neovim is about 15mb, while vscode takes up 200 Mb by itself. The difference of 30 Mb it takes to package 2 extra versions seems like it won't affect things for the majority of users.

2. Security doesn't seem to me like it would be a serious concern here, although I don't think I have a good understanding of the space. I think the extension model used in Vscode /atom is inherently insecure, and I don't see why adding a binary would change things. Basically, any extension can already run arbitrary code, so I don't think including an additional binary would affect security much.

I do think that downloading the required version would be a better solution, I'm just not sure how much extra work /unreliable it would be.
